apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: admeshion-system

resources:
- namespace.yaml
- serviceaccount.yaml
- deployment.yaml
- service.yaml

labels:
  app.kubernetes.io/name: admeshion
  app.kubernetes.io/instance: admeshion-gateway

images:
- name: admeshion/gateway
  newTag: latest
