apiVersion: v1
kind: ServiceAccount
metadata:
  name: admeshion-gateway
  namespace: admeshion-system
  labels:
    app: admeshion-gateway
    app.kubernetes.io/name: admeshion
    app.kubernetes.io/component: gateway
