apiVersion: v1
kind: Service
metadata:
  name: admeshion-gateway
  namespace: admeshion-system
  labels:
    app: admeshion-gateway
    app.kubernetes.io/name: admeshion
    app.kubernetes.io/component: gateway
spec:
  selector:
    app: admeshion-gateway
  ports:
  - name: webhook
    port: 443
    targetPort: webhook
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: metrics
    protocol: TCP
  type: ClusterIP
